[package]
name = "json-rs"
version = "0.0.1"

[dependencies]
memmap = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[profile.release]
lto = true

[[bin]]
name = "json-value-rs"
path = "src/json_value.rs"

[[bin]]
name = "json-struct-rs"
path = "src/json_struct.rs"

[[bin]]
name = "json-pull-rs"
path = "src/json_pull.rs"
